### ISSUE TITLE
KSP 1.1 Checklist

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RealismOverhaul#1120]
Here is a checklist for the KSP 1.1 update. We are now **merged down to master. All changes should be done on master now**.

**Required/Recommended Mods RO needs**

A check means "Not our problem" basically--that updating is either complete or in progress and therefore we don't have to take it on ourselves.

- [x] Procedural Fairings - dependent on @e-dog
- [x] Procedural Parts - dependent on @ItMustBeACamel
- [x] B9 Proc Wings - dependent on @Crzyrndm
- [x] AJE - NK and @blowfishpro
- [x] FAR
- [x] KJR
- [x] RealChute
- [x] RealFuels - NK, @taniwha, @Starwaster, @jwvanderbeck 
- [x] RealHeat - NK, @ferram4 - depends on how much we want to do.
- [x] SmokeScreen - @sarbian, please x when ready!
- [x] Deadly Reentry - @Starwaster https://github.com/Starwaster/DeadlyReentry/releases/tag/v7.4.0
- [x] Connected Living Space - @codepoetpbowden and @PapaJoesSoup any idea of status?
- [x] Hangar Extender - @alewx and in progress.
- [ ] Procedural Fairings for Everything - will need an update once PF updates, I think. @Felger ?
- [x] RemoteTech - large group of folks and will probably need a lot of work.
- [x] SemiSaturatableRW - shouldn't need much updating. @Crzyrndm please x when ready!
- [ ] TacLifeSupport - @Taraniselsu my understanding is that we are updating it? Or do you still have interest in (helping) port to 1.1?
- [x] Texture Replacer - handled by @dukacar
- [ ] Ven's Stock Revamp - handled by @VenVen
- [ ] Reflection plugin (used by FASA etc). @Starwaster 

**Config Changes**
- [ ] Take advantage of built-in vernier support (requires model changes in many cases however: all thrust transforms must be named the same but there must be separately named FX transform sets for main nozzle(s) and vernier nozzle(s))
- [x] Take advantage of new axis-limited gimbal support
- [ ] Ohgodwheels. The numbers will need ROizing in most cases.
- [ ] Blacklist existing tutorials and scenarios (they won't work in RO-land), eventually make our own.
- [ ] KSPedia! Move some wiki info into KSPedia
- [x] Change everything with a ModuleResource to report something sane in GetInfo (I'll do examples, since I wrote the code).
- [x] Change solar panel flow to show in watts.
- [x] Have occlusion change convective coeff not shock temp (requires plugin work, probably best done by RealHeat anyway)
- [ ] Part tagging! We need to decide on our own tags, nuke original tags as needed, etc.
- [ ] Related: Manufacturers pass. We need to specify the real manufacturer on parts.
- [x] RESCALEFACTOR IS SAFE! That will make our life easier.
- [x] Change our heat shields over to converting Ablator into CharredAblator.

**Deferred Items from 1.0.5**
- [ ] Update docking ports to use snap angles and gendered setting.
- [ ] Set up a proper kerbal drag cube (and, possibly, rescale kerbals?). Change kerbal RCS thrust.
- [ ] Tune hatch obstruction check raycast distance for new part sizes.
- [ ] Apply cylindrical and spherical solar panel mode where appropriate.
- [ ] Use added scaling variables to rescale IVAs and the kerbals in them.

**Comment by stratochief66** [comment]
This was meant to be useful for making this list; perhaps it was:
https://docs.google.com/spreadsheets/d/1STypNuCUo6OzFW7XhUPDQhMtLNLR6i0HaLwh9_yfRmw/edit#gid=0

**Comment by PapaJoesSoup** [comment]
updates in work for CLS and SM.

**Comment by jwvanderbeck** [comment]
Wow lots of mentions.  I almost feel left out :p

Since I have TestFlight pretty much ready to go other than some UI overhauls I want to do, I am free to help out in other areas.  I'm not great with configs but could maybe look into the KSPedia stuff.  Or maybe update some engine models if we have the source models?

**Comment by NathanKell** [comment]
@stratochief66 yes it was, and yes it will be! :) Although I somehow forgot persistent rotation, but that's all good cause it's ready.

@PapaJoesSoup awesome! :)

@jwvanderbeck maybe because you have your stuff together? :D And that's awesome to hear! I'll chat with you in RO about where might be best to work on--I know @taniwha pushed what he has on RF so maybe tackling that first, especially since it's linked to TF, might make the most sense.

**Comment by jwvanderbeck** [comment]
Ah yeah if he pushed his changes that makes sense.  I'll take a look.

**Comment by blowfishpro** [comment]
B9 is a bit blocked right now so I can probably start taking a look at AJE.  I don't think it will require a lot of changes.

**Comment by jwvanderbeck** [comment]
Shoudl maybe spin off an issue to discuss and decide on tagging

**Comment by Crzyrndm** [comment]
@NathanKell 
Updates for all of the mods I maintain (including Semi-sat RW and B9 Proc wings) will happen closer to 1.1 release date (probably next weekend or the week after). I don't have the time currently to be testing 1.1, nevermind updating mods for it.

**Comment by blowfishpro** [comment]
AJE is nominally working now.  Not extensively tested, but all the basic stuff seems to work.

**Comment by jwvanderbeck** [comment]
RealFuels is good to go.

**Comment by ItMustBeACamel** [comment]
Greetings!
Yes, I'm alive and I will update PParts over the course of the week. :)

**Comment by NathanKell** [comment]
@blowfishpro that's great to hear!
@Crzyrndm That makes sense. Since the proc wings use bac9's own system, presumably running on IMGUI, it should not take much in the way of updating.
@jwvanderbeck woot! :)
@ItMustBeACamel awesome! Really happy to hear that! :) Created an issue on the PP repo to track things.

**Comment by sarbian** [comment]
SmokeScreen is out : https://ksp.sarbian.com/jenkins/job/SmokeScreen/54/

**Comment by NathanKell** [comment]
Hurrah!

**Comment by stratochief66** [comment]
I've unchecked FAR at Ferram's suggestion. we should also possibly have MFI listed here, as FAR depends on it.

**Comment by jwvanderbeck** [comment]
Doesn't MFI already have a 1.1 version?

**Comment by sarbian** [comment]
it does

**Comment by e-dog** [comment]
@NathanKell @ItMustBeACamel Proc Fairings seem to work after initial rebuild, but I disabled attach node position change event needed for Proc Parts (because it was using KSPAPIExtensions). Does anyone know what should I do about that?

Also UI_FloatEdit is not what it used to be with KSPAPIExtensions, but I didn't look into that yet.

**Comment by jwvanderbeck** [comment]
@e-dog What taniwha (don't know Github name) has done with MFT is use the underlying Unity events system that is exposed/reimplemented by KSP.

For example: https://github.com/NathanKell/ModularFuelSystem/blob/master/Source/Tanks/FuelTank.cs#L95

**Comment by ItMustBeACamel** [comment]
@e-dog I would say, keep it like that for now. I will send you a PR if that Event is still necessary.

**Comment by Crzyrndm** [comment]
SSRW is recompiled for 1.1. Can be grabbed from my github (no releases till KSP is officially updated)

**Comment by Felger** [comment]
For Procedural Fairings for Everything, my methodology shouldn't actually need much updating, all I do is copy the parts that PF uses and modify them ever so slightly.  Assuming Firespitter gets updated to 1.1 it should just need a version update.

I'll check in on how the parts actually end up working out, whether those have been rescaled.

**Comment by raidernick** [comment]
Can we add the reflection plugin to this list. I had a chat about this with @stratochief66 and seeing as how both my mod and FASA(which has an offical RO release now) heavily rely on it's use and the plans to add the engines pack to RO to replace the stock ones for 1.1. Currently it causes massive problems with the game and has not been updated since 0.23.

**Comment by jwvanderbeck** [comment]
Is it even necessary to continue hacking our way around this?  I'm guessing we should be able to just load the standard reflection shader more directly now using an AssetBundle.

**Comment by raidernick** [comment]
I know nothing about the assestbundles or shaders. I have the latest part tools and have been scratching my head so far on exactly how to actually do anything with them. Based on the responses on the forums this seems to be a general consensus. Someone is going to actually have to make a step by step explaination of how to do this, like porkjet since he actually did the work on them. Is this something that is done in unity to the parts themselves? Is it something that is done with a plugin to directly access the shaders? It is something that can be done using an existing part module? I have no idea.

**Comment by jwvanderbeck** [comment]
Well for just parts you are correct you don't want to mess with the new stuff.  Just thinking that the old hacky way of getting the shader in, which as you pointed out no longer works, might no longer be necessary.  Instead we should  be able to simply place the standard reflection shaders into an AssetBundle and load them with a plugin.

How that gets referenced from the parts, I don't know.  How did it work with the old mod?

**Comment by raidernick** [comment]
The old mod created a part module where you could define the shader, specular color and reflection color for individual mesh objects. This is imperative as you usually don't want to reflect an ENTIRE part, just specific parts of that part.

**Comment by Zarbizaure** [comment]
For my part, Forgotten Real Engines will be updated for KSP 1.1 once Realism Overhaul will be.

**Comment by NathanKell** [comment]
Updated the issue. Coders and cfgs, please please do that last section first--I need to know what fails to work so I can fix it before pre ends.

**Comment by NathanKell** [comment]
Some more detail on those things:
- DateTimeFormatter: Create a new class that implements IDateTimeFormatter and then replace the existing one (In KSPUtils) on start of MainMenu. Talk to @NathanKell or @eggrobin or @taniwha for details.
- Modify convective coefficient rather than shock temp in occlusion (done in RealHeat). Set the static public stuff in OcclusionCone during Start of MainMenu, say. Change the shock temp mults to always 1, and instead change the convective coeff mults.
- Different thrust per transform: convert vernier'd parts to single-engine-module parts (cfg). Try on KVD-1 by going back to original LR-1R models, not edited ones. See forum thread (engine info for modders) in the 1.1 Pre Modding forum.
- Set ModuleAblator to create CharredAblator from Ablator (cfg), increase ablator consumption rate dramatically for LEO shields. Try on Mk1 pod. Multiply lossConst by 40 and divide pyrolysisLossFlux by 40, then add `outputResource = CharredAblator` to the module and add a RESOURCE { name = CharredAblator amount = 0 maxAmount = [whatever ablator amount is] } Give that a test.
- Set different +/- X,Y ranges for gimbals (cfg). Try on LR101. See aforementioned engine thread for details.
- Experiments can have cooldown timers (cfg). Try on film camera. Add cooldownTimer = (time in seconds) to the MODULE.
- Experiments can be set to not work when shielded (cfg). Try on film camera. Add availableShielded = False to the MODULE.
- Verify Warp-To-Morning throughout the solar year in RSS. Should warp to ~7am.

**Comment by stratochief66** [comment]
I'm still trying to parse this with my morning brain.

I warped to morning on Y1D3, it warped to 12h35m. The sun is fairly close to the horizon, but with scatterer I can't precisely tell how close. Hitting it again shortly after warps just a few minutes, again same thing (about 15 minutes) then the next time around to ~12h58m which appears to be within an hour of actual sunset, sun still very/fairly low in the sky. 

Does testing of this nature need to wait until something else has been completed?

**Comment by jwvanderbeck** [comment]
I had assumed the 7am would be local time?

**Comment by NathanKell** [comment]
1. Pushed cfg changes for the first two items (solar panel related) to the branch.
2. Last week I started working on the DateTime thing (in RSS) but did not get very far, and will not be able to. Here's what I have. http://hastebin.com/ehoqukaliq.coffee

**Comment by NathanKell** [comment]
7am is, or should be, local time, yes. This means that it should be warping to a consistent UT if Earth's sidereal rotation period is correct.

**Comment by stratochief66** [comment]
@NathanKell On the solar panel display:
https://www.dropbox.com/s/auv2lyts5cx5bk3/screenshot5.png?dl=0

Works. Looks like a space is missing between the units and the value. Showing 1 digit past the decimal, which seems ideal for RO.

**Comment by NathanKell** [comment]
Cool. Can you tweak the RO_Global to add the space back? Also maybe use N1 instead of F1 so there is a units separator (so it's easy to see where the kW end and the W begin, when >1000W)

**Comment by NathanKell** [comment]
Oh son of a....can't add the space back. Confignodes. I'll do it on my end.

**Comment by NathanKell** [comment]
Still, the F1->N1 change. Worth doing?

**Comment by NathanKell** [comment]
MOAR replies! Ok, in the next prerelease build, set flowUnitsUseSpace = True in the MODULE.

**Comment by anxcon** [comment]
- Experiments can be set to not work when shielded (cfg). Try on film camera

works on stock experiment, didn't have other stuff installed to test on

**Comment by stratochief66** [comment]
Set different +/- X,Y ranges for gimbals (cfg). Try on LR101.

Works. I will put up a PR for it soon.

**Comment by stratochief66** [comment]
Set ModuleAblator to create CharredAblator from Ablator (cfg), increase ablator consumption rate dramatically for LEO shields...

I used the numbers suggested, 73 units of ablator transformed from high suborbital speed (~5km/s?) and the mass of the craft stayed constant. Any suggestions or leads on how to move off of a 1:1 transformation? ie. some Ablator should be lost, not converted to Char. @NathanKell

**Comment by NathanKell** [comment]
Right now CharredAblator is [set up to mass .975 what regular Ablator does](https://github.com/KSP-RO/RealismOverhaul/blob/KSP11Update/GameData/RealismOverhaul/RO_Resources.cfg#L8), which means out of 80 ablator charred the vessel should have lost 2kg.

**Comment by NathanKell** [comment]
Warp to morning is still not behaving correctly... >.>

**Comment by NathanKell** [comment]
RealHeat updated on the repo.

**Comment by jwvanderbeck** [comment]
https://github.com/KSP-RO/RSSTimeFormatter

First pass at TimeDate formatter

**Comment by NathanKell** [comment]
<3

**Comment by jwvanderbeck** [comment]
https://github.com/KSP-RO/RSSTimeFormatter/releases/tag/1.0.0.0

**Comment by sgrif** [comment]
Do y'all need any additional manpower to get this pushed through? I have very little experience with KSP mods, but am an engineer who worked in .NET full time in a past life. Happy to help if there's anything I can do.

**Comment by NathanKell** [comment]
@sgrif we do indeed! Thank you! We've actually got some serious work to do on TACLS since AFAIK @TaranisElsu has passed it over to us and isn't updating it for 1.1.

**Comment by sgrif** [comment]
Happy to take it on. Is the process here roughly: See if it compiles against 1.1, fix compiler errors until it does, and then manually test the DLL? I'm assuming automated test suites are uncommon for KLP mods?

**Comment by taraniselsu** [comment]
Yeah, sorry, I have not had time to work on my mods for 1.1, and I will be too busy over the next 2 weeks to do anything either.

@cherrydev created an issue on TACLS about 1.1 support, you might check with them to see how far they got: https://github.com/taraniselsu/TacLifeSupport/issues/90

I appreciate any work that any of you contribute. I will work on doing a proper handoff when things settle down at the end of the month.

**Comment by cherrydev** [comment]
Short story: It seems to work just fine after I target the new KSP/Unity DLLs and modify the API usage as described in Squad's document that describes how to update mods for 1.1, but so far I'm the only one who's tested it.  Somebody should probably also make it work with the stock toolbar.

**Comment by jwvanderbeck** [comment]
> Somebody should probably also make it work with the stock toolbar.

For the love of god yes.  This mod is literally the only mod that I still need the old toolbar for.

**Comment by Crzyrndm** [comment]
Confirming SSRW has a 1.1 release with no known issues (other than new features I haven't enabled yet)
B9PW also has a release but has some visual issues due to a workaround for stock control surfaces no longer supporting -ve mirror scaling correctly (see [this](http://forum.kerbalspaceprogram.com/index.php?/topic/137449-control-surfaces-moving-in-wrong-directions/) thread for details)

**Comment by NathanKell** [comment]
@cherrydev that's great news! I was very worried.

@sgrif sounds like work on TACLS might not be needed, but there are plenty of other coding tasks! At the moment the next "big thing" code wise is RP-0 and in particular some of the proc part integration we want to do with it and with TestFlight. You interested in that? The other RP-0 thing is 'naut training, because that fell by the wayside as I got caught in 1.1 crunch. See [here](http://forum.kerbalspaceprogram.com/index.php?/topic/131381-requestidea-kerbal-training-and-other-time-based-kerbal-mechanics/) -- interested in that?

**Comment by NathanKell** [comment]
@Crzyrndm woot! Also, poking Claw about that issue you describe.

**Comment by NathanKell** [comment]
@cherrydev will you be releasing a temporary release for CKAN?

**Comment by cherrydev** [comment]
Well, I had hoped that @taraniselsu would have taken what I sent him and made a release but I know he's really busy and probably hasn't had time to do it.  I will try to take some time in the next few days to get something suitable for release happen.  I guess I've never made a release to CKAN but it looks like I just make a PR to KSP-CKAN/NetKAN.

**Comment by sgrif** [comment]
@NathanKell I'm at a conference for the rest of the week but I'd be happy to pitch in once that's done

**Comment by NathanKell** [comment]
**PSA**

We are now merged down to master! Please make all PRs to the master branch!

**Comment by NathanKell** [comment]
I have begun writing the changelog. It currently reads:

* Update for KSP 1.1.2!
* Update to latest RealPlume.
* Start axis-limiting gimbals.
* Show ElectricCharge in watts in tooltips and the Solar Panel menu in flight.
* Heat shields make much more sense now: they convert ablator into charred ablator, and "consume" untouched ablator at more sensible rates.
* Gendered many docking ports.
* RemoteTech tweaks.
* Do a pass to mention diameter and correct manufacturer for various parts.
* And many more

What else should be added?

**Comment by NathanKell** [comment]
Closed in favor of #1242 .
