### ISSUE TITLE
Engines checklist

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RealismOverhaul#144]
- [x] Constelacion -> J-2X
- [x] Fix 1kn and 0.5kn thrusters to obey propellant thrust scaling (and the AIES one to be 2kN base since 2 nozzles). That means call it 1kN class, maybe? Since with NTO/AZ50 it'll be more like 2kN...
- [x] Give the above (generic thrusters) EngineIgnitor configs; pressure-fed unlimited-restart ullage=false.
- [x] Backport VSR engines
- [x] Add LR-105-3
- [x] Port over VSR-engine changes (to SquadEngines) to other same-config engines
- [x] mea culpa: CECE should be an RL10 alt config, not a new part.
- [x] RLA Kingfisher -> Bell 8xxx engine/Agena engine (was CECE)
- [x] RLA Albatross -> VINCI (was J-2)
- [x] KW Globe X-10S "Thor II" SRB -> 5-seg Shuttle SRB (was UA-1207)
- [x] Set AIES Exper to RL-60 (was RL-10B-2)

Regarding the generic thrusters: Right now, RCS configs (check out an RCS module) have differing thrust and Isp based on what propellant mixture is used; coldgas has low thrust and Isp, hydrazine is decent, and storable hypergolics are quite good indeed. The "generic thruster" parts, however, only increase Isp based on propellant change, not thrust. They should be scaled in thrust as well, like RCS.

**Comment by NathanKell** [comment]
Possibles:
- [ ] Set Exper to RL-60 or CECE not RL10B-2

**Comment by jwvanderbeck** [comment]
Working on the first right now.  Have the base configs in place need to test in game to ensure proper scaling (which will no doubt make me want to punch babies)

**Comment by NathanKell** [comment]
I'm working on the backport for the record, about 1/4 done, although right now I'm dealing with figuring out what happened to RLA.

**Comment by jwvanderbeck** [comment]
You also need to let me know what I should do with the RLA J-2.  Either keep it as the J-2 line but remove the J-2X, or make it a J-2X only engine and remove the J-2 line.

**Comment by jwvanderbeck** [comment]
Which mixture should be the "1.0" point on the generic thrusters?  The 0.5kN thruster in RLA seems to have already been done and its 1.0 point is in the MMH+NTO mixture.  Yet when I look at say the Squad RCS, the 1.0 point is in the Hydrazine mixture.

**Comment by jwvanderbeck** [comment]
@NathanKell "KW Globe X-10S "Thor II" SRB -> 5-seg Shuttle SRB (was UA-1207)" did you mean the 4-segment that was actually flown, or the proposed 5-segment one that would have been used for Ares?

**Comment by jwvanderbeck** [comment]
"Set AIES Exper to RL-60 (was RL-10B-2"

The RL-60 was originally being designed in two models, a 40,000 lbs and 60,000 lbs version.  The 40k version was to be the Vinci, but got put on hold.  Given the huge increase in thrust from the RL10 to the RL60, I think we should provide two configs, one for the Vinci lower thrust version and then the full RL60.  On a tangential note the MB-60 is basically an RL-60 assembled in Japan.  P&W and Mitsubishi jointly developed the RL-60.

Reference: http://www.rocket-propulsion.info/resources/articles/RL_60.pdf

Proposal: Make an RL-60 part named RL-60, but with configs for "Vinci-180" and "RL-60"

**Comment by NathanKell** [comment]
@jwvanderbeck 
1. Hydrazine should be the baseline config (1.0 for the 1kNs, 0.5 for the 0.5kN, and 2 for the DES thruster from AIES).
2. Yes, the 5seg for Ares. We already have 4-segment SSRBs.
3. The RLA Albatross is to become the Vinci, so I don't see the need to dual-config the RL-60 (unless MB-60 has different stats), though I'm not at all set on it.
