### ISSUE TITLE
1.0.5 Checklist

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RealismOverhaul#671]
1.0.5 adds a bunch of useful thingies relevant to our lives. I'm going to continuously update this OP as more checklist items get added (and more get checked off, one hopes). Please feel free to assign yourself, either by editing (if a collab) or by posting a comment, and a collab will edit it into the OP.

- [x] Adjust Physics.cfg values for RO use. Note that crossfeeding for STACK_PRI can be toggled, and the actual physics constants and FX constants need updating. @NathanKell
- [x] Remove RO Shroud Toggle, functionality is stock now.
- [x] Rebalance heat shields (again). @NathanKell (and @stratochief66  ?)
- [x] Revert to ModuleRCS since it basically _is_ ModuleRCSFX now.
- [x] Update any DRAG_CUBE overrides - there are quite a few in stock KSP, and if we rescale parts we need to update drag cube areas and extents.
- [x] Remove Crossfeed Enabler
- [x] Add ModuleToggleCrossfeed to appropriate parts (mod decouplers? What else?)
- [x] Disable intakes and jets when under water (will be done by AJE, so no worries.)
- [x] Update all AJE-configured parts to have correct propellants (AJE no longer does this).
- [x] Add hypothetical configuration for the RAPIER and best-guess for the SABREs.
- [x] Support new parts. (Vector, Panther, Goliath, Mk1 crew cabin, Mk3 mount and ramp, maybe add the new Mk1 cockpit as a new part, and keep using Ven's old cockpit? Wut do?)

---

**Related Mod Dependent Items**

- [x] Coordinate with @Starwaster regarding RF boiloff, and with him and @toadicus regarding any refrigeration code.
- [x] Add RP-0 entry costs and technodes for all added CONFIGs for engines.

---

**Deferred Items**
- [ ] Update docking ports to use snap angles and gendered setting.
- [ ] Set up a proper kerbal drag cube (and, possibly, rescale kerbals?). Change kerbal RCS thrust.
- [ ] Tune hatch obstruction check raycast distance for new part sizes.
- [ ] Apply cylindrical and spherical solar panel mode where appropriate.
- [ ] Use added scaling variables to rescale IVAs and the kerbals in them.

**Comment by stratochief66** [comment]
Once we have Kopernicus up again, I am all up for working heatshields

**Comment by NathanKell** [comment]
Awesome. I'll check with @ThomasKerman tomorrow.

**Comment by NathanKell** [comment]
Not listed here, but supported the Mk3 engine mount and ramp. The other new parts still need configs.

**Comment by PhineasFreak** [comment]
ModuleRCSFX is included with the standalone Realism Overhaul installation zip file. Shouldn't we remove it now since it's deprecated?

**Comment by NathanKell** [comment]
@PhineasFreak Yeah I need to update the netkan for that. Good point.

In other news, RSS is working with dev Kopernicus! Just made my first RO orbit in 1.0.5.

**Comment by Olympic1** [comment]
00d8e61 and fc7ffa8 break the RO release of KSP 1.0.4. It is better that you update the netkan file **after** the release, as this file will be checked every ~3 hours. If you could revert these commits and add them back in after the release, that would be very helpfull.

**Comment by winged7** [comment]
New 1.0.5 jet engines - P&P for RP-0

https://github.com/KSP-RO/RP-0/pull/364

**Comment by NathanKell** [comment]
Ok. As of the latest commit ( 20c0a63295bdbafe07260997b0b472157dcdf3ea ) please

# consider RO in Release Candidate mode.

**Comment by winged7** [comment]
P&P for new 1.0.5 parts:
https://github.com/KSP-RO/RP-0/pull/376

Update for entryCostModifiers:
https://github.com/KSP-RO/RP-0/pull/377

**Comment by stratochief66** [comment]
@NathanKell anything from this list that you want to keep as 'To Do's for 1.1?

Or else, close?

**Comment by NathanKell** [comment]
All the deferred items still need to be done, but there should be a new issue made, good point. :)
