### ISSUE TITLE
SSTU_RO Issue tracking and resolution thread

### ISSUE THREAD

**Issue by stratochief66** [KSP-RO/RealismOverhaul#888]
To Fix:
- [ ] Run through all engines, config for RF
- [ ] Clean up RealPlume configs to all share the same style (I have used different code styles as I have learned RealPlumes better)

Specifically, the new form shuttle SRBs need to have the old shuttle SRBs attached to them instead.
- [x] Check new SRBs for substantial inconsistency with the type. ie. Huge mass differences, huge ISP differences.

Resolved:
- [x] Achieve clean seperation for docking and transposition of Orion CM. Currently, the stand the CM sits on does not break into parts and separate. Also, a stack decoupler may be necessary for building  a craft (?) which also doesn't break into parts.
  #883 Possibly entirely resolved here, we will see
- [x] Disable the reaction wheel on Orion CM 
  #889
- [x] The 2 of 3 SM RCS now appears to consume Monoprop again, fix.
  #889
- [x] Lower the mass of the petal fairing by about an order of magnitude.
  #889
- [x] Alter Orion Crossfeed. SM RCS should not feed from Orion CM @NathanKell, what mode might achieve this?
  #936
- [x] Add an upper internal EUS node so that it can slot into the interstage petal adapter hollow base.
  #936

**Comment by Zarbizaure** [comment]
I though SSTU should work like Ven's stock part revamp, instead of just adding new parts; or at least, it should overwrite the old engines so that we don't have twice the same part.

**Comment by stratochief66** [comment]
SSTU has too much additional function to really make that possible. Plus, who are we to decide which of the various mods has the best version of an engine? For some engines, there are at least 3 or more various mods that include their own version of an engine. I think we have to leave it to the user to pick which one they like best.

Naturally, that doesn't stop someone else from making a mod that selectively prunes engines like that, relying on RO to configure all the options :)

**Comment by Zarbizaure** [comment]
yes, that's what I meant. Dealing with tons of engines from various mods is a pain and not easy for basics users (but I know, RO players aren't "basic" players). I'm not great at modding, but if somebody has time to spare to create that mod (though I could help, I just don't know how to create a mod from scratch), it will give RO a better organization - what it actually lacks of.

**Comment by stratochief66** [comment]
[18:24] <NathanKell> that said, if you just want to stop RCS drawing, override flow in the RCS PROPELLANT nodes as you were thinking

[18:22] <NathanKell> use the same flow mode that SolidFuel has when overriding (IIRC it's NO_FLOW ?)

**Comment by Cooboo117** [comment]
Oh also (This is a really really small one) Make sure that the ICPS is a cryogenic tank. When I found my way into its Cfg it noticed it was a default tank.

**Comment by stratochief66** [comment]
@Cooboo117 They are pretty similar, and the definition of the default tank has been dancing around a little bit in the past month or two. In fact, perhaps it should be a balloon tank in the real fuel tank world, since the ICPS has very little insulation, such that they simply stretched the LH2 tank (to hold more) to deal with boiloff during the pre-TLI coast rather than insulation.

**Comment by stratochief66** [comment]
Theysen: 
so when you cluster engines via the right click menu, MJ shows correct TWR values etc, ingame though it considered as one engine only and gives according low thrust for that stage

there are also 2 "Show GUI" for the engine in the VAB, one changing the whole stack, the other one seems to change it for one engine only and the inflight low TWR is shown in MJ

**Comment by stratochief66** [comment]
Modular RSRM 2 seg ran pretty much exactly 10s ISP behind the real one, and weighs 1T more as well.

**Comment by stratochief66** [comment]
Unrelated, probably an old bug. RS-68 cluster base config calls for oxidizer and doesn't scale with increasing numbers of engines. The F-1, J-2, RS-25, etc. work well, so the RS-68 just needs to be configured in that style.

**Comment by Max-Q** [comment]
The file SSTU_SRB.cfg handled parts which were deprecated and are now removed in SSTU-0.3.30-pre2. The file should probably be removed too.

**Comment by stratochief66** [comment]
@Max-Q agreed. I plan to find and remove redundant configs and code as of 1.1, since at present I don't believe they are doing any harm.

**Comment by stratochief66** [comment]
Most of the realplumes exist in RO, just not attached to the new part names. I just haven't had the time or interest to move them over.

Anybody interested could probably be shown how to do it relatively quickly, or if they have any RealPlume experience at all figure it out themselves.

**Comment by Temeter** [comment]
In the current RO release, Realplumes doesn't seem to work at all for SSTU engines, they always run on stock plumes. Stock (using the patches delivered by the mod) works just fine.

**Comment by stratochief66** [comment]
We scale the parts up, so they will need new plumes or plume modification.
I did this previously, but SSTU has since changed pretty much all the part
names so it will need to be revisitted and the old plumes either revised or
removed.

@SirKeplan?

**Comment by Temeter** [comment]
Hm, I copied over the SSTU stock plume config of an F1 over, and replaced the numbers by the old RO stats (Flarescale->Fixedscale). Seems mostly fine. Does it work that way, or lucky accident?

**Comment by stratochief66** [comment]
Hard to say, it has been a long time for me. You are free to try it and see
if you keep getting lucky :)

**Comment by Temeter** [comment]
Yeah, seems like the old configs still work, you just need to change the names. More problematic, there are a bunch of new engines. Gotta look what I can do...

**Comment by stratochief66** [comment]
Can you send up the updates for the old ones you got working as a PR (Pull
Request), then your work on new ones can be a separate PR?

**Comment by Temeter** [comment]
I'll do, just gotta check some more. Isn't much work, literally just changing names, since the old configs apparently still work.

Still going at least to take a loof if I can't just replace the whole RO patches with a modified version of the SSTU configs... In that case, it might just be some scaling.

**Comment by Temeter** [comment]
Ok, the engines I changed all work! How do I create a pull request? I found the button, but I'm not sure how to chose the files to switch up and change them.

**Comment by stratochief66** [comment]
Go to the proper file in the Github, for example:
https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RealPlume_Configs/SSTU/SSTU_ShipCore_ENG-F1.cfg

Click the Pencil (Edit) button, and put in the changes you needed to make
for it to work.

Add some details to the commit name & description (for example, updated F1
SSTU plume for KSP 1.1.2)

Create a pull request from that commit (is likely just a button, but might
require slightly more)

**Comment by Temeter** [comment]
Done. Github is quite tricky to see through. 

I've also now learned that there are different Realplume formats for RO and Stock, that was the thing that confused me.
#1227

**Comment by stratochief66** [comment]
RO doesn't really have a standardized format for RealPlumes. At least, I
also see different types from different times. Really, whatever works,
works. Ideally, something that is easy to understand is good as well.

**Comment by Temeter** [comment]
I see. That's usefull to know!

**Comment by Temeter** [comment]
So, just went ahead and added plumes for all compatible LFO engines.
#1230

Checked them ingame, but I'd like for someone experienced to look them over. First time I edited plumes, and they basically needed to be completely rescaled.

**Comment by blowfishpro** [comment]
I've been adjusting all the default sizes and increments to conform to multiples of 1m rather than stock sizes.  So far have been adjusting the min diameter and increment to be 0.5m (there's a larger increment which SSTU makes double the increment, and finer adjustment which is done at 1/20 of the increment).  I've been mostly using 4m for the default size but are there better default diameters to use for the various parts?

Other possible issues I've noticed:

* The modular SRBs seem to have some issues: The engine GUI can't be opened and MechJeb spams exceptions with it.  Have not yet looked into the cause
* Are the pre-built engine clusters necessary?  I currently see a 5x F-1 and 5x SSME.  All those configurations can be accessed through SSTU's adjustments
* Ditto the pre-sized boosters, assuming the above issues can be fixed.
* The Apollo service module is titled "AJ1-0137", whereas it is an entire service module (not just an engine).  I can fix this easily, just wanted to know if there was any justification for the naming.

**Comment by stratochief66** [comment]
The answer for why specific instances exist in SSTU is pretty much always
"because then specific recreation parts can be set to their exact and
accurate masses and burn times"

I'll let other people answer the other parts of your questions,if they
choose to.

**Comment by SirKeplan** [comment]
@blowfishpro No justification, generally stages/service modules should be named after the whole thing, not the engine.
it probably happened accidentally when i added the template engine configs.

**Comment by SirKeplan** [comment]
@stratochief66 is the RSRMV mass still an issue? no reason the mass should go as high as 113.5t
if i understand this source right, dry mass should only be about 85.4t
https://web.archive.org/web/20131125063755/http://www.atk.com/wp-content/uploads/2013/02/ATK-Motor-Catalog-2012.pdf (p 67)

**Comment by stratochief66** [comment]
Not sure SirKeplan, I haven't looked in a long time.

**Comment by Temeter** [comment]
I think all engines, including those with placeholder modells, are now configured for RO and RealPlume!

We also got correct mass and price adjustment for multi-engine slots now.
